
#define FACTION NONE

#define LOADOUT_VAR(NAME) CONCAT3(f_loadouts_,CONCAT(FACTION,_),NAME)
#define ADD_VARIANT(NAME,LOADOUT) LOADOUT_VAR(NAME) pushBack LOADOUT
#define CREATE_LOADOUT(NAME,LOADOUT) LOADOUT_VAR(NAME) = []; ADD_VARIANT(NAME,LOADOUT)
#define COPY_LOADOUT(NAME,OTHERNAME) LOADOUT_VAR(NAME) = LOADOUT_VAR(OTHERNAME)
