
#define FACTION NONE

#define LOADOUT_VAR(NAME) CONCAT3(f_loadouts_,CONCAT(FACTION,_),NAME)

#define LOADOUT_ITEM_VAR(NAME,ITEM) CONCAT3(LOADOUT_VAR(NAME),_,ITEM)
#define LOADOUT_ITEM_VAR_DYNAMIC(SIDE,NAME,ITEM) (missionNamespace getVariable [format ["f_loadouts_%1_%2_%3", SIDE, NAME, ITEM], []])

#define HATS_DYNAMIC(SIDE,NAME) LOADOUT_ITEM_VAR_DYNAMIC(SIDE,NAME,"hats")
#define VESTS_DYNAMIC(SIDE,NAME) LOADOUT_ITEM_VAR_DYNAMIC(SIDE,NAME,"vest")
#define UNIFORMS_DYNAMIC(SIDE,NAME) LOADOUT_ITEM_VAR_DYNAMIC(SIDE,NAME,"uniforms")
#define BACKPACKS_DYNAMIC(SIDE,NAME) LOADOUT_ITEM_VAR_DYNAMIC(SIDE,NAME,"backpack")

#define ADD_VARIANT(NAME,LOADOUT) LOADOUT_VAR(NAME) pushBack LOADOUT

#define HATS(NAME) LOADOUT_ITEM_VAR(NAME,hats)
#define VESTS(NAME) LOADOUT_ITEM_VAR(NAME,vest)
#define UNIFORMS(NAME) LOADOUT_ITEM_VAR(NAME,uniforms)
#define BACKPACKS(NAME) LOADOUT_ITEM_VAR(NAME,backpack)

#define ADD_HAT(NAME,ITEM) HATS(NAME) pushBack ITEM
#define ADD_VEST(NAME,ITEM) VESTS(NAME) pushBack ITEM
#define ADD_UNIFORM(NAME,ITEM) UNIFORMS(NAME) pushBack ITEM
#define ADD_BACKPACK(NAME,ITEM) BACKPACKS(NAME) pushBack ITEM

#define CREATE_LOADOUT(NAME,LOADOUT)\
    LOADOUT_VAR(NAME) = [];\
    HATS(NAME) = [];\
    VESTS(NAME) = [];\
    UNIFORMS(NAME) = [];\
    BACKPACKS(NAME) = [];\
    ADD_VARIANT(NAME,LOADOUT)

#define COPY_ADDONS(NAME,OTHERNAME)\
    HATS(NAME) = +HATS(OTHERNAME);\
    VESTS(NAME) = +VESTS(OTHERNAME);\
    UNIFORMS(NAME) = +UNIFORMS(OTHERNAME);\
    BACKPACKS(NAME) = +BACKPACKS(OTHERNAME)

#define COPY_LOADOUT(NAME,OTHERNAME)\
    LOADOUT_VAR(NAME) = +LOADOUT_VAR(OTHERNAME);\
    COPY_ADDONS(NAME,OTHERNAME)
