
BEGIN_IDENTITY_ASSIGNMENT;

SET_FACTION_IDENTITY(opfor,brit);
SET_FACTION_IDENTITY(blufor,yank);
SET_FACTION_IDENTITY(indfor,greek);
SET_FACTION_IDENTITY(guerilla,monke);
SET_FACTION_IDENTITY(civilian,coward);