
#define FACTION blufor


// Zeus squad
MAKE_SQUAD_EDITABLE(ZEUS);
HIDE_SQUAD(ZEUS);

MAKE_SQUAD_EDITABLE(ALPHA);
SET_SQUAD_COLOUR(ALPHA,RED);
SET_SQUAD_NAME(ALPHA,"Alpha");

MAKE_SQUAD_EDITABLE(BRAVO);
SET_SQUAD_ICON(BRAVO,MECHINF);
SET_SQUAD_COLOUR(BRAVO,BLUE);
SET_SQUAD_NAME(BRAVO,"Beavo");
