
#define IDD_VIEWDISTANCE_DIALOG 12146

#define IDC_VIEWDISTANCE_TERRAINSLIDER 1900
#define IDC_VIEWDISTANCE_TERRAINVALUE 1400

#define IDC_VIEWDISTANCE_OBJECTSLIDER 1901
#define IDC_VIEWDISTANCE_OBJECTVALUE 1401

#define IDC_VIEWDISTANCE_SHADOWSLIDER 1902
#define IDC_VIEWDISTANCE_SHADOWVALUE 1402

#define IDC_VIEWDISTANCE_TERRAINCOMBO 2100
