
#define IDC_DOWNTIMEDEAD_SUBTITLE 1002

#define IDC_DOWNTIMERESPAWN_HEADER 1000
#define IDC_DOWNTIMERESPAWN_REASON 1002
#define IDC_DOWNTIMERESPAWN_INSTRUCTION 1001
#define IDC_DOWNTIMERESPAWN_DISCLAIMER 1100
