
f_map_slot_shortcodes = createHashMapFromArray
[
	["squad leader", "SL"],
	["section leader", "SL"],
	["fireteam leader", "FTL"],
	["team leader", "TL"],
	["2ic", "2IC"],
	["2nd in command", "2IC"],
	["second in command", "2IC"],
	["deputy leader", "2IC"],
	["co", "CO"],
	["command", "CO"],
	["commander", "CO"],
	["xo", "XO"],
	["executive officer", "XO"],
	["fac", "FAC"],
	["forward air control", "FAC"],
	["forward air controller", "FAC"],
	["light anti tank", "LAT"],
	["light anti-tank", "LAT"],
	["light at", "LAT"],
	["anti tank", "AT"],
	["anti-tank", "AT"],
	["medium anti tank", "MAT"],
	["medium anti-tank", "MAT"],
	["medium at", "MAT"],
	["heavy anti tank", "HAT"],
	["heavy anti-tank", "HAT"],
	["heavy at", "HAT"],
	["autorifleman", "AR"],
	["autorifle", "AR"],
	["machinegunner", "MG"],
	["light machinegunner", "LMG"],
	["medium machinegunner", "MMG"],
	["heavy machinegunner", "HMG"],
	["medic", "MED"],
	["combat lifesaver", "CLS"],
	["corpsman", "CLS"],
	["surgeon", "Surg."],
	["demolitions", "DEMO"],
	["demoman", "DEMO"],
	["demolitions expert", "DEMO"],
	["demo expert", "DEMO"],
	["engineer", "ENGI"],
	["logistics", "LOGI"],
	["assistant anti tank", "AAT"],
	["assistant anti-tank", "AAT"],
	["assistant at", "AAT"],
	["assistant lat", "ALAT"],
	["assistant mat", "AMAT"],
	["assistant hat", "AHAT"],
	["assistant autorifle", "AAR"],
	["assistant autorifleman", "AAR"],
	["assistant ar", "AAR"],
	["assistant machinegunner", "AMG"],
	["assistant mg", "AMG"],
	["assistant mmg", "AMMG"],
	["assistant hmg", "AHMG"],
	["ammo bearer", "AMMO"],
	["rifleman", "RIF"],
	["pilot", "Pilot"],
	["heli pilot", "Pilot"],
	["heli crew", "Crew"],
	["crew chief", "Crew"],
	["copilot", "Copilot"],
	["vehicle commander", "CMD"],
	["vehicle gunner", "GUN"],
	["gunner", "GUN"],
	["driver", "DRV"],
	["sniper", "SN"],
	["spotter", "SPOT"],
	["marksman", "MK"],
	["designated marksman", "MK"]
];

f_map_slot_icons = createHashMapFromArray
[
	["SL", "SL"],
	["FTL", "SL"],
	["TL", "SL"],
	["2IC", "SL"],
	["CO", "CO"],
	["CMD", "CO"],
	["XO", "OFFICER"],
	["FAC", "OFFICER"],
	["AR", "AR"],
	["MG", "AR"],
	["LMG", "AR"],
	["MMG", "AR"],
	["AT", "AT"],
	["LAT", "AT"],
	["MAT", "AT"],
	["HAT", "AT"],
	["MED", "MED"],
	["CLS", "MED"],
	["Surg.", "MED"],
	["DEMO", "DEMO"],
	["ENGI", "ENG"],
	["LOGI", "ENG"]
];

f_map_slot_restricted = createHashMapFromArray
[
	["SL", true],
	["FTL", true],
	["TL", true],
	["2IC", true],
	["CO", true],
	["XO", true],
	["FAC", true],
	["MED", true],
	["Surg.", true],
	["DEMO", true],
	["ENGI", true],
	["LOGI", true],
	["Pilot", true],
	["CMD", true],
	["SN", true]
];